hydra:
  run:
    dir: ./outputs/geo_default/${datamodule.obj_class}

datamodule:
  root_dir: /mnt/public/datasets/zhenjun/VTacO_Track/v00
  obj_class: "001"
  tracking: True  
  train_all: False   
  sample_point_num: 2048  
  sample_pc_num: 512  
  pc_noise: 0.005
  batch_size: 6
  num_workers: 4

trackingmodule_path: /mnt/homes/zhenjun/vtaco_v2/config/train_tracking_corr_flow.yaml

geo_param:
  assets_dir: /mnt/homes/zhenjun/vtaco_v2/assets
  sensor_sample_mode: anchor
  threshold_dist: 0.01
  k_repl: 0.1
  optimize_item: ["hand"]
  loss_item: 
    Energy: [0.5, 1e4]
    # sdf_off: 1
    hand_off: 1
  max_steps: 100
  lr: 0.003

trainer:
  gpus: [1]
  max_steps: 100
  resume_from_checkpoint: /mnt/homes/zhenjun/vtaco_v2/outputs/tracking_corr_flow/${datamodule.obj_class}/checkpoints/last.ckpt