hydra:
  run:
    dir: ./outputs/vtacotracking_touch/003

datamodule_name: ViTaMDataModule
datamodule:
  root_dir: /mnt/public/datasets/zhenjun/vitam_glove_data/v01
  obj_class: "001"
  tracking: True  
  train_all: False   
  sample_point_num: 2048  
  sample_pc_num: 2048  
  pc_noise: 0.005
  batch_size: 8
  num_workers: 4

trackingmodule_name: ForceTrackingPipeline
trackingmodule:
  anchor_param:
    assets_dir: /mnt/homes/zhenjun/vtaco_v2/assets
    sensor_sample_mode: anchor

  training_param:
    optimizer: "Adam"
    lr: 0.0001
    
  pointnet_param:
    nn_channels: [3, 16, 32, 48]
    feature_transform: False
  
  mlp_force_param:
    nn_channels: [12, 32, 64]

  transformer_force_param:
    use_xyz: True
    input_size: 4000
    d_model: 64
    num_layers: 1
    key_feature_dim: 64
    with_pos_embed: True
    encoder_pos_embed_input_dim: 3
    decoder_pos_embed_input_dim: 3
    fea_channels: [64, 64, 32]
    feat_slim_last_layer: True
  
  transformer_param:
    use_xyz: True
    input_size: 4000
    d_model: 32
    num_layers: 1
    key_feature_dim: 32
    with_pos_embed: True
    encoder_pos_embed_input_dim: 3
    decoder_pos_embed_input_dim: 3
    fea_channels: [32, 32, 32]
    feat_slim_last_layer: True

  unet3d_param:
    num_levels: 4
    f_maps: 32
    in_channels: 32
    out_channels: 32
  
  grid_param:
    reso_grid: 64
    grid_dim: 32
    padding: 0.1
    sample_mode: bilinear
  
  decoder_param:
    input_dim: 3
    hidden_size: 32
    n_blocks: 5
  
  vis_param:
    vis_every: 1
    nx: 128
    vis_point_every_split: 100000
    print_time: True

  loss_items: {"sdf": 1, "hand": 1}
  
  hand_decoder_param:
    pointnet_param:
      nn_channels: [3, 64, 128, 256]
      feature_transform: False
    mlp_param:
      nn_channels: [256, 128, 51]
    manolayer_param: 
      center_idx: 0
      flat_hand_mean: True
      ncomps: 45
      side: right
      mano_root: /mnt/homes/zhenjun/vtaco_v2/components/manopth/mano/models
      use_pca: False
      root_rot_mode: axisang
      joint_rot_mode: axisang
      robust_rot: False
      return_transf: True
      return_full_pose: True


trainer:
  gpus: [1]
  check_val_every_n_epoch: 1
  max_epochs: 101
  # max_steps: 30000
  resume_from_checkpoint: ./checkpoints/last.ckpt